nomal="R0lGODlhCAAIAMIBAAAAADs7O4+Pj9nZ2Ts7Ozs7Ozs7Ozs7OyH+EUNyZWF0ZWQgd2l0aCBHSU1QACH5BAEKAAQALAAAAAAIAAgAAAMVGDBEA0qNJyGw7AmxmuaZhWEU5kEJADs="
hover="R0lGODlhCAAIAMIEAAAAAP/SAP/bNNnZ2cbGxsbGxsbGxsbGxiH5BAEKAAQALAAAAAAIAAgAAAMVGDBEA0qNJyGw7AmxmuaZhWEU5kEJADs="
press="R0lGODlhCAAIAMIEAAAAAOUqKv9mZtnZ2Ts7Ozs7Ozs7Ozs7OyH+EUNyZWF0ZWQgd2l0aCBHSU1QACH5BAEKAAQALAAAAAAIAAgAAAMVGDBEA0qNJyGw7AmxmuaZhWEU5kEJADs="

### 将来
# 編集中ファイルの通常状態
active_from_notepad: str ="Qk3CAQAAAAAAADYAAAAoAAAACwAAAAsAAAABABgAAAAAAIwBAAAAAAAAAAAAAAAAAAAAAAAApoysfWeegGufgWufgGqgfmqhe2mkeWakdWOjc2ChoYSm/3//fmushnGujHavjHavinWvh3Swg3KxfW6yeGqyc2Wvcl2f////hG6ujXaw////////kHmxi3eyhnWz////////dWexcl+j////iHCukniv////////////jXix////////////eGiwdmCi/7//jXSul3uvmXyw////////////////////fWuxfGivemGh////k3ivm32wmn2wlnmv////////////gGqufWmufmitfGGe/3//l3uvnoGwm32w////////////////////fmetgGmsfmKf////nH+wo4ax////////////jHGu////////////g2mrf2Od////ooWwrI2y////////l3mukXWujHGt////////hGmrfWGb/7//ro+yt5ezq4yxo4Wwn4Gwm36vmnyvlXmuj3Othmure1+b////wJ+1q42yn4Owm3+vl3uvlXmvk3iuj3StiW+sgWeqooGn/3//"
# 非編集中ファイルの通常状態
inactive_from_notepad="Qk3CAQAAAAAAADYAAAAoAAAACwAAAAsAAAABABgAAAAAAIwBAAATCwAAEwsAAAAAAAAAAAAArq6ulZWVl5eXmJiYl5eXl5eXl5eXlpaWlJSUkpKSqqqqAAAAmpqan5+foqKioqKioqKioqKioKCgnp6enJycmZmZkpKSAAAAnp6epKSk2dnZ2dnZpqampaWlpKSk2dnZ2dnZm5ublJSUAAAAoqKip6en2dnZ2dnZ2dnZp6en2dnZ2dnZ2dnZnZ2dlpaWAAAApaWlqampq6ur2dnZ2dnZ2dnZ2dnZ2dnZoKCgnp6emJiYAAAAqKiorKysq6urqamp2dnZ2dnZ2dnZoKCgn5+fn5+fmZmZAAAAq6urrq6urKys2dnZ2dnZ2dnZ2dnZ2dnZn5+foKCgmpqaAAAAra2tsbGx2dnZ2dnZ2dnZpaWl2dnZ2dnZ2dnZoKCgm5ubAAAAsLCwtra22dnZ2dnZqqqqp6enpaWl2dnZ2dnZoaGhmpqaAAAAt7e3vb29tra2sbGxr6+vrq6ura2tq6urqKiooqKimZmZAAAAwcHBtra2sLCwra2tq6urqqqqqampp6enpaWloKCgsLCwAAAA"

hover_from_notepad="Qk3CAQAAAAAAADYAAAAoAAAACwAAAAsAAAABABgAAAAAAIwBAAAAAAAAAAAAAAAAAAAAAAAAf4ruN0jePU7gP1DgQlXjRlvlRl/rR2LuQV3uN1Lpe4nnAAAAP1L7TF78Vmf8WWv9YHX9Z4H9aon+Zon+W4H+THD9NVHp/7//S13/Wmv/////////b4T/d5H/epv/////////WH/+Plvu////VGX/ZXX/////////////fJb/////////////YIX+SGTw/3//X2//bn3/coH/////////////////////a47/YoL+TGXs////aXj/d4b/d4b/coL/////////////ZYH/YH3/XXj+TGHo////c4L/go//fYv/////////////////////VGv/Vmz9SVvl/7//fIr/jZn/////////////ZHT/////////////UmT9R1fi////iJX/m6b/////////d4X/bHv/YnL/////////U2X9RVXh/3//mqX/rLX/mqX/jZn/hZL/f4z/eYf/cYH/Z3f/WGn9QlLh////t7//lqH/hJH/fIr/dYT/cYD/bn3/Z3f/Xm//UGL9hpHv////"

push_from_notepad="Qk3CAQAAAAAAADYAAAAoAAAACwAAAAsAAAABABgAAAAAAIwBAAAAAAAAAAAAAAAAAAAAAAAAboDHGzy8HD2/HD2/HT7AHkHDH0PFH0TGIEbIH0TGcojaAGAAFzOhGzy8HD2+HT7AHUDCH0TGIUfJIknMIkrNIUnLH0TGAGAAFzKeGzy8iZ3iiZ3iHkHDIEXHIknLiZ3iiZ3iIkrNIEXHAKAAFjGaGzy7iZ3iiZ3iiZ3iIETHiZ3iiZ3iiZ3iIkrMH0TGAGAAFS+WGzq5Gzu7iZ3iiZ3iiZ3iiZ3iiZ3iIkrMIUfKH0PFALAAFC2NGji0Gjm6Gzu8iZ3iiZ3iiZ3iH0THIEXHH0TGHkHDAEAAEyuIGTauGji2iZ3iiZ3iiZ3iiZ3iiZ3iHkDCHUDCHT7AAGAAEih+FzOmiZ3iiZ3iiZ3iGzq8iZ3iiZ3iiZ3iHT7AHD2/AGAAESV2FjCciZ3iiZ3iGTe1Gjm5Gzq7iZ3iiZ3iHD2+HD2/ARQAECNtFC2RFjCdFzOnGTauGji0Gzq4Gzu7Gzy7Gzy8Gzy8////Z3GXDyJrECRyESd7FCuKFCyMFS+VFjGaFzKfFzKfboDH///+"
